### Open-WebUI-Dev | https://github.com/open-webui/open-webui
### Postgres | https://www.postgresql.org/
### ChromaDB | https://docs.trychroma.com/

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./.open-webui-data:/app/backend/data
#     - /path/to/your/docs:/app/backend/data/docs 
      - ./.open-webui-data/config.json:/app/backend/data/config.json  
      - ./.open-webui-data/litellm/config.yaml:/app/backend/data/litellm/config.yaml       
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - chromadb
    environment:
      - 'SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS}'
      - 'DO_NOT_TRACK=${DO_NOT_TRACK}'
      - 'ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY}'
      - 'LITELLM_LOCAL_MODEL_COST_MAP=${LITELLM_LOCAL_MODEL_COST_MAP}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'DATABASE_URL=${DATABASE_URL}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
      - 'CHROMA_HTTP_HOST=${CHROMA_HTTP_HOST}'
    restart: unless-stopped
    
  chromadb:
    image: docker.io/chromadb/chroma:latest
    container_name: open-webui-chromadb
    environment:
      - 'ALLOW_RESET=${ALLOW_RESET}'
      - 'ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY}'
      - 'CHROMA_ROOT_PASSWORD=${CHROMA_ROOT_PASSWORD}'
      - 'CHROMA_DATABASE=${CHROMA_DATABASE}'
      - 'CHROMA_HTTP_HOST=${CHROMA_HTTP_HOST}'
    ports:
      - "3308:3306"
    volumes:
      - ./.open-webui-data/.data-chroma:/chroma/chroma
      - ./.open-webui-data/.data-chroma:/app/data
    restart: unless-stopped      

  postgres:
    container_name: open-webui-postgres
    image: docker.io/postgres:latest
    environment: 
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_PORT=${POSTGRES_PORT}'
      - 'POSTGRES_DB=${POSTGRES_DATABASE}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports: 
      - "5333:5432"
    volumes:
      - ./.open-webui-data/.data-postgres:/var/lib/postgresql/data
    restart: unless-stopped
