# Open-WebUI-Dev-Cuda | https://github.com/open-webui/open-webui
# Searxng | https://github.com/searxng/searxng
# Watchtower | https://containrrr.dev/watchtower/
# Pipelines | https://github.com/open-webui/pipelines

services:
  watchtower:
    image: containrrr/watchtower
    container_name: open-webui-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WATCHTOWER_POLL_INTERVAL: 600
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
    command: open-webui-dev-cuda
    restart: always
    networks:
      - "hyperspace"
      
  open-webui-dev-cuda:
    image: ghcr.io/open-webui/open-webui:dev-cuda
    container_name: open-webui-dev-cuda
    ports:
      - "3000:8080"
    volumes:
      - ./.data-open-webui:/app/backend/data
      - ./.data-open-webui/config.json:/app/backend/data/config.json  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu      
    extra_hosts:
      - "host.docker.internal:host-gateway"     
    environment:
      - 'SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS}'
      - 'DO_NOT_TRACK=${DO_NOT_TRACK}'
      - 'ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'USE_CUDA_DOCKER=${USE_CUDA_DOCKER}'
    restart: always
    networks:
      - "hyperspace"

  searxng:
    image: searxng/searxng:latest
    container_name: open-webui-searxng
    ports:
      - "4000:8080"      
    volumes:
      - ./.data-searxng:/etc/searxng:rw
    depends_on:
      - open-webui-dev-cuda       
    restart: always  
    networks:
      - "hyperspace"
      
  pipelines:
    image: ghcr.io/open-webui/pipelines:main 
    container_name: open-webui-pipelines
    ports:
      - "9099:9099"
#    environment:
#      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
#      COHERE_API_KEY: "${COHERE_API_KEY}"
#      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
#      PIPELINES_URLS: "${PIPELINES_URLS}"
    volumes:
      - ./.data-pipelines:/app/pipelines
    depends_on:
      - open-webui-dev-cuda    
    restart: always
    networks:
      - "hyperspace"
      
networks:
  hyperspace:
    external: true
